<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	function search($word){
		return $this->createQueryBuilder('p')
			->where('p.title like :word')
			->setParameter('word' , '%'.$word.'%')
			->getQuery()
			->getResult()
		;
	}
}
